name: Deploy Pipe Server

on: 
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
  TF_VAR_DO_TOKEN: ${{ secrets.DO_TOKEN}}
  TF_VAR_MYSQL_DB: ${{ secrets.MYSQL_DB}}
  TF_VAR_MYSQL_HOST: ${{ secrets.MYSQL_HOST}}
  TF_VAR_MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD}}
  TF_VAR_MYSQL_USER: ${{ secrets.MYSQL_USER}}


jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps: 
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8
          terraform_wrapper: false

      - name: Create SSH Keys from secrets
        run: |
            mkdir keys
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./keys/pipe_server
            echo "${{ secrets.SSH_PUBLIC_KEY }}" > ./keys/pipe_server.pub
            chmod 777 ./keys/pipe_server
            chmod 777 ./keys/pipe_server.pub
      - name: Terraform Init
        run: terraform init

      - name: Terraform format
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply --auto-approve

